services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "${BACK_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
