services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "${BACK_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_BROKER_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    env_file:
      - .env
  
  celery:
    build: ./back
    command: >
      sh -c "celery -A back worker --loglevel=info"
    volumes:
      - ./back:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
  
  front:
    build:
      context: ./front
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "${FRONT_PORT}:5173"
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - back

volumes:
  postgres_data:
