# Generated by Django 5.2.3 on 2025-06-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasklist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='repeat_after_minutes',
            new_name='repeat_after_seconds',
        ),
    ]
